=== myrjone/SMP/SMP/data/nurserostering/import/competition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by SSS (.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>
      Schema for personnel scheduling problems.
    </xs:documentation>
  </xs:annotation>
  <xs:element name="SchedulingPeriod">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CourseTypes" type="CourseTypes"/>
        <xs:element name="Coordinators" type="Coordinators"/>
        <xs:element name="CoordinatorToCourseType" type="CoordinatorToCourseType"/>
        <xs:element name="Contracts" type="Contracts"/>
        <xs:element name="Tas" type="Tas"/>
        <xs:element name="CoverRequirements" type="CoverRequirements"/>
        <xs:element name="CourseOffRequests" type="CourseOffRequests" minOccurs="0"/>
        <xs:element name="CourseOnRequests" type="CourseOnRequests" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ID" type="xs:string" use="required"/>
      <xs:attribute name="OrganisationID" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="CourseTypes">
    <xs:sequence>
      <xs:element name="Course" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
            <xs:element name="StartTime" type="xs:time"/>
            <xs:element name="EndTime" type="xs:time"/>
            <xs:element name="Dept" type="xs:string" minOccurs="0"/>
            <xs:element name="Crs" type="xs:string" minOccurs="0"/>
            <xs:element name="Sec" type="xs:string" minOccurs="0"/>
            <xs:element name="Bldg" type="xs:string"/>
            <xs:element name="Rm" type="xs:string"/>
            </xs:element>
          </xs:all>
          <xs:attribute name="ID" type="ID" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Coordinators">
    <xs:sequence>
      <xs:element name="Coordinator" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Email" type="xs:string" minOccurs="0"/>
            <xs:element name="CourseTypeID" type="ID"/>
          </xs:all>
          <xs:attribute name="ID" type="ID" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CoordinatorToCourseType">
    <xs:sequence>
      <xs:element name="Mapping" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
            <xs:element name="CoordinatorId" type="ID"/>
            <xs:element name="CourseTypeID" type="ID"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Contracts">
    <xs:sequence>
      <xs:element name="Contract" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
            <xs:element name="SingleAssignmentPerDay" type="WeightOnly" minOccurs="0"/>
            <xs:element name="MaxNumAssignments" type="OnAndWeight" minOccurs="0"/>
            <xs:element name="MinNumAssignments" type="OnAndWeight" minOccurs="0"/>
            <!-- (Implemented in parser only) -->
            <!-- TODO remove this! -->
            <xs:element name="Description"/>
          </xs:all>
          <xs:attribute name="ID" type="ID" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Tas">
    <xs:sequence>
      <xs:element name="Ta" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
            <xs:element name="ContractID" type="ID"/>
            <xs:element name="Name" type="xs:string" minOccurs="0"/>
            <xs:element name="Email" type="xs:string" minOccurs="0"/>
          </xs:all>
          <xs:attribute name="ID" type="ID" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConstraintAttributes">
    <xs:attribute name="on" type="xs:boolean" use="optional"/>
    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional"/>
  </xs:complexType>
  <xs:complexType name="OnAndWeight">
    <xs:simpleContent>
      <xs:extension base="xs:nonNegativeInteger">
        <xs:attribute name="on" type="xs:boolean" use="optional"/>
        <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="WeightOnly">
    <xs:simpleContent>
      <xs:extension base="xs:boolean">
        <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CoverRequirements">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="DayOfWeekCover">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Day" type="WeekDay"/>
            <xs:element name="Cover" type="Cover" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="DateSpecificCover">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Date" type="xs:date"/>
            <xs:element name="Cover" type="Cover" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="Cover">
    <xs:sequence>
      <xs:choice>
        <xs:element name="Course" type="ID"/>
      </xs:choice>
      <xs:element name="Preferred" type="xs:nonNegativeInteger" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CourseOffRequests">
    <xs:sequence>
      <xs:element name="CourseOff" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CourseTypeID" type="ID"/>
            <xs:element name="TaID" type="ID"/>
            <xs:element name="Date" type="WeekDay"/>
          </xs:sequence>
          <xs:attribute name="weight" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CourseOnRequests">
    <xs:sequence>
      <xs:element name="CourseOn" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:choice>
              <xs:element name="CourseTypeID" type="ID"/>
            </xs:choice>
            <xs:element name="TaID" type="ID"/>
            <xs:element name="Date" type="WeekDay"/>
          </xs:sequence>
          <xs:attribute name="weight" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="WeekDay">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Sunday"/>
      <xs:enumeration value="Monday"/>
      <xs:enumeration value="Tuesday"/>
      <xs:enumeration value="Wednesday"/>
      <xs:enumeration value="Thursday"/>
      <xs:enumeration value="Friday"/>
      <xs:enumeration value="Saturday"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="WeekDayOrAny">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="ID">
    <xs:restriction base="xs:string">
      <xs:pattern value="([a-zA-Z0-9._])+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== myrjone/SMP/SMP/data/nurserostering/import/sprint01.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<SchedulingPeriod ID="sprint01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="competition.xsd">
  <CourseTypes>
    <Course ID="00000">
      <StartTime>08:00:00</StartTime>
      <EndTime>09:50:00</EndTime>
      <Dept>CHEM</Dept>
      <Crs>124A</Crs>
      <Sec>001</Sec>
      <Bldg>BL</Bldg>
      <Rm>1165</Rm>
    </Course>
    <Course ID="00001">
      <StartTime>10:00:00</StartTime>
      <EndTime>11:50:00</EndTime>
      <Dept>CHEM</Dept>
      <Crs>124A</Crs>
      <Sec>001</Sec>
      <Bldg>BL</Bldg>
      <Rm>1165</Rm>
    </Course>
    <Course ID="00002">
      <StartTime>12:00:00</StartTime>
      <EndTime>13:50:00</EndTime>
      <Dept>CHEM</Dept>
      <Crs>124A</Crs>
      <Sec>001</Sec>
      <Bldg>BL</Bldg>
      <Rm>1165</Rm>
    </Course>
    <Course ID="00003">
      <StartTime>14:00:00</StartTime>
      <EndTime>15:50:00</EndTime>
      <Dept>CHEM</Dept>
      <Crs>124A</Crs>
      <Sec>001</Sec>
      <Bldg>BL</Bldg>
      <Rm>1165</Rm>
    </Course>
    <Course ID="00004">
      <StartTime>14:00:00</StartTime>
      <EndTime>15:50:00</EndTime>
      <Dept>CHEM</Dept>
      <Crs>124A</Crs>
      <Sec>001</Sec>
      <Bldg>BL</Bldg>
      <Rm>1165</Rm>
    </Course>
    <Course ID="00005">
      <StartTime>14:00:00</StartTime>
      <EndTime>15:50:00</EndTime>
      <Dept>CHEM</Dept>
      <Crs>124A</Crs>
      <Sec>001</Sec>
      <Bldg>BL</Bldg>
      <Rm>1165</Rm>
    </Course>
    <Course ID="00006">
      <StartTime>14:00:00</StartTime>
      <EndTime>15:50:00</EndTime>
      <Dept>CHEM</Dept>
      <Crs>124A</Crs>
      <Sec>001</Sec>
      <Bldg>BL</Bldg>
      <Rm>1165</Rm>
    </Course>
  </CourseTypes>
  <Coordinators>
      <Coordinator ID="0">
        <Name>Senator Palpatine</Name>
        <Email>palp@republic.gov</Email>
      </Coordinator>
      <Coordinator ID="1">
        <Name>Senator Palpatine</Name>
        <Email>palp@republic.gov</Email>
      </Coordinator>
  </Coordinators>
  <CoordinatorToCourseType>
      <Mapping>
          <CoordinatorId>0</CoordinatorId>
          <CourseTypeId>00000</CourseTypeId>
      </Mapping>
      <Mapping>
          <CoordinatorId>0</CoordinatorId>
          <CourseTypeId>00001</CourseTypeId>
      </Mapping>
  </CoordinatorToCourseType>
  <Contracts>
    <Contract ID="0">
      <Description>Standard TA Contract</Description>
      <MaxNumAssignments on="1" weight="1">2</MaxNumAssignments>
      <MinNumAssignments on="1" weight="1">1</MinNumAssignments>
    </Contract>
  </Contracts>
  <Tas>
    <Ta ID="0">
      <ContractID>0</ContractID>
      <Name>Furlow, Scott</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="1">
      <ContractID>0</ContractID>
      <Name>Peterson, Luke</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="2">
      <ContractID>0</ContractID>
      <Name>Hooper, Alex</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="3">
      <ContractID>0</ContractID>
      <Name>Jones, Myron</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="4">
      <ContractID>0</ContractID>
      <Name>Bouvier, Dennis</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="5">
      <ContractID>0</ContractID>
      <Name>White, William</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="6">
      <ContractID>0</ContractID>
      <Name>Crk, Igor</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="7">
      <ContractID>0</ContractID>
      <Name>Yu, William</Name>
      <Email>apple</Email>
    </Ta>
    <Ta ID="8">
      <ContractID>0</ContractID>
      <Name>Mayer, Gary</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
    <Ta ID="9">
      <ContractID>0</ContractID>
      <Name>Gamage, Thosita</Name>
      <Email>temp@siue.edu</Email>
    </Ta>
  </Tas>
  <CoverRequirements>
      <CourseCover>
          <Course>00000</Course>
          <Preferred>2</Preferred>
          <Days>
              <Day>Monday</Day>
              <Day>Tuesday</Day>
          </Days>
      </CourseCover>
      <CourseCover>
          <Course>00001</Course>
          <Preferred>1</Preferred>
          <Days>
              <Day>Monday</Day>
          </Days>
      </CourseCover>
      <CourseCover>
          <Course>00002</Course>
          <Preferred>1</Preferred>
          <Days>
              <Day>Wednesday</Day>
          </Days>
      </CourseCover>
      <CourseCover>
          <Course>00003</Course>
          <Preferred>1</Preferred>
          <Days>
              <Day>Wednesday</Day>
              <Day>Friday</Day>
          </Days>
      </CourseCover>
  </CoverRequirements>
  <CourseOffRequests>
    <CourseOff >
      <CourseTypeID>00000</CourseTypeID>
      <TaID>0</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00001</CourseTypeID>
      <TaID>4</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00002</CourseTypeID>
      <TaID>5</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00003</CourseTypeID>
      <TaID>6</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00001</CourseTypeID>
      <TaID>7</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00004</CourseTypeID>
      <TaID>8</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00005</CourseTypeID>
      <TaID>9</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00002</CourseTypeID>
      <TaID>2</TaID>
    </CourseOff>
    <CourseOff >
      <CourseTypeID>00003</CourseTypeID>
      <TaID>3</TaID>
    </CourseOff>
  </CourseOffRequests>
  <CourseOnRequests>
      <CourseOn weight="1">
          <CourseTypeID>00001</CourseTypeID>
          <TaID>0</TaID>
    </CourseOn>
  </CourseOnRequests>
</SchedulingPeriod>
